### ISSUE TITLE
Bug in normal gwei value

### ISSUE THREAD

**Issue by loganbek** [wslyvh/ethgaswatch#10]
@wslyvh, I was using the service today and noticed a bug in the Normal gas price value. I've attached a screenshot of the issue where the normal value seems incorrect:  

<img width="1235" alt="Screen Shot 2021-04-26 at 1 15 18 AM" src="https://user-images.githubusercontent.com/9355004/116051658-ac562d00-a62d-11eb-9dce-be6a3a93af2f.png">

As you can see the normal gas value should be somewhere between 36 and 47. Let me know if I can supply any other info to help debug.

**Comment by wslyvh** [comment]
All the data is coming from other/3rd-party data sources. They're returning gas prices of 6. Unclear why this is happening, But I assume they're using the same methods for calculating gas prices. 

This usually gets filtered out by taking the median. It seems like too many sources have been reporting badly at this point though

**Comment by wslyvh** [comment]
Removed a few (deprecated) sources. Haven't seen 6 gwei values anymore after either.

Closing for now..
