### ISSUE TITLE
Better methodology needed

### ISSUE THREAD

**Issue by teohhanhui** [wslyvh/ethgaswatch#5]
Currently it can produce insensible results. See screenshot.

![Screenshot_20210112-021617](https://user-images.githubusercontent.com/548843/104221860-7923cf80-547c-11eb-8af6-7c56e87a8e35.png)

**Comment by wslyvh** [comment]
This is unfortunately an issue with data coming from the other API's. Also see #4 
There are some checks in place to filter out anomalies. The aggregated results should provide more reliable estimates than any of the other sources independently. But it will always remain a bit tricky during peak times (as screenshotted). Most of them are using the same calculation mechanisms and they're all still estimates that can change any block.

If you have any specific suggestions, let me know!

**Comment by wslyvh** [comment]
Removed a few (deprecated) sources. Seems to be more reliable since then.

So closing this issue for now..
