### ISSUE TITLE
How to use api trend

### ISSUE THREAD

**Issue by ximo1984** [wslyvh/ethgaswatch#6]
It's not clear how to use api trend:
https://docs.ethgas.watch/api#trend

It needs a parameter to use amount of days but it not has name. Can you help me and show me and example of call it?

Thanks in advance.

**Comment by wslyvh** [comment]
Good catch. I need to update the documentation.

In the meantime, you can call the API using either a `days` or `hours` querystring param.

e.g. 
https://ethgas.watch/api/gas/trend?days=7
Which will get you the trend data of last 7 days

https://ethgas.watch/api/gas/trend?hours=24
Which will get you the trend data of last 24 hrs

**Comment by ximo1984** [comment]
Thank you :)

**Comment by wslyvh** [comment]
Updated the documentation now as well.
https://docs.ethgas.watch/api

Thanks for reporting!
