### ISSUE TITLE
Api call blocked by missing Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by alexkeating** [wslyvh/ethgaswatch#9]
I am trying to call the ethwatch.gas api from my react app with the below code and am getting the following error. Is this expected? 

Code:
```
  const response = await axios.get(
    `https://ethgas.watch/api/gas/trend?hours=168`,
  );
```

Error
<img width="678" alt="Screen Shot 2021-04-19 at 10 42 02 AM" src="https://user-images.githubusercontent.com/12705146/115255045-e7230700-a0fb-11eb-8e5f-1535ab82b9d9.png">

**Comment by wslyvh** [comment]
Have you tried calling it from your own back-end/service? 

If you're calling the service from the client-side, then you might indeed run into a CORS issue. As only ethgas.watch itself is a known origin.

**Comment by alexkeating** [comment]
Thank you for the reply! The app I am working on has no backend and is client side only app. Is it possible to change the allowed origin to be more permissive?

**Comment by wslyvh** [comment]
CORS has its benefits, even though the API only has GET methods and doesn't mutate anything.
This way, it also requires a bit of effort for other projects to consume the services. Which also prevents anyone to just spam the service.

So I'm a bit hesitant to just allow anyone.
But I did update the 3 endpoints described in the [docs](https://docs.ethgas.watch/api) to allow all (*) for now.
Should make it work for you.

I'll continue to monitor traffic and usage.
